// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/fpl.proto

package customer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00519c44ffdc0ef5, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00519c44ffdc0ef5, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type NumPlayerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumPlayerRequest) Reset()         { *m = NumPlayerRequest{} }
func (m *NumPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*NumPlayerRequest) ProtoMessage()    {}
func (*NumPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00519c44ffdc0ef5, []int{2}
}

func (m *NumPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumPlayerRequest.Unmarshal(m, b)
}
func (m *NumPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumPlayerRequest.Marshal(b, m, deterministic)
}
func (m *NumPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumPlayerRequest.Merge(m, src)
}
func (m *NumPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_NumPlayerRequest.Size(m)
}
func (m *NumPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NumPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NumPlayerRequest proto.InternalMessageInfo

type NumPlayers struct {
	NumPlayers           int64    `protobuf:"varint,1,opt,name=numPlayers,proto3" json:"numPlayers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumPlayers) Reset()         { *m = NumPlayers{} }
func (m *NumPlayers) String() string { return proto.CompactTextString(m) }
func (*NumPlayers) ProtoMessage()    {}
func (*NumPlayers) Descriptor() ([]byte, []int) {
	return fileDescriptor_00519c44ffdc0ef5, []int{3}
}

func (m *NumPlayers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumPlayers.Unmarshal(m, b)
}
func (m *NumPlayers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumPlayers.Marshal(b, m, deterministic)
}
func (m *NumPlayers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumPlayers.Merge(m, src)
}
func (m *NumPlayers) XXX_Size() int {
	return xxx_messageInfo_NumPlayers.Size(m)
}
func (m *NumPlayers) XXX_DiscardUnknown() {
	xxx_messageInfo_NumPlayers.DiscardUnknown(m)
}

var xxx_messageInfo_NumPlayers proto.InternalMessageInfo

func (m *NumPlayers) GetNumPlayers() int64 {
	if m != nil {
		return m.NumPlayers
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "customer.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "customer.HelloReply")
	proto.RegisterType((*NumPlayerRequest)(nil), "customer.NumPlayerRequest")
	proto.RegisterType((*NumPlayers)(nil), "customer.NumPlayers")
}

func init() { proto.RegisterFile("grpc/fpl.proto", fileDescriptor_00519c44ffdc0ef5) }

var fileDescriptor_00519c44ffdc0ef5 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x14, 0xc4, 0x77, 0x59, 0x71, 0xd7, 0x87, 0x88, 0x3c, 0x44, 0x96, 0x3d, 0x88, 0xe4, 0x20, 0x1e,
	0xa4, 0x42, 0xbd, 0x79, 0x57, 0x7b, 0x90, 0xb6, 0xd4, 0x4f, 0x90, 0x96, 0xd7, 0x5e, 0x92, 0x26,
	0xe6, 0xcf, 0x21, 0xdf, 0x5e, 0x08, 0x4d, 0x5b, 0xdc, 0x5b, 0x66, 0x98, 0x99, 0xfc, 0x78, 0x70,
	0x33, 0x18, 0xdd, 0xbd, 0xf6, 0x5a, 0x64, 0xda, 0x28, 0xa7, 0xf0, 0xd0, 0x79, 0xeb, 0x94, 0x24,
	0xc3, 0x18, 0x5c, 0x17, 0x24, 0x84, 0x6a, 0xe8, 0xd7, 0x93, 0x75, 0x88, 0x70, 0x31, 0x72, 0x49,
	0xc7, 0xed, 0xe3, 0xf6, 0xf9, 0xaa, 0x89, 0x6f, 0xf6, 0x04, 0x30, 0x65, 0xb4, 0x08, 0x78, 0x84,
	0xbd, 0x24, 0x6b, 0xf9, 0x90, 0x42, 0x49, 0x32, 0x84, 0xdb, 0xd2, 0xcb, 0x5a, 0xf0, 0x40, 0x66,
	0xda, 0x63, 0x2f, 0x00, 0xb3, 0x67, 0xf1, 0x01, 0x60, 0x9c, 0x55, 0xac, 0xef, 0x9a, 0x95, 0x93,
	0x7f, 0xc0, 0xfe, 0xcb, 0x10, 0x39, 0x32, 0xf8, 0x0e, 0x87, 0x1f, 0x1e, 0xe2, 0xbf, 0x78, 0x9f,
	0x25, 0xde, 0x6c, 0x0d, 0x7b, 0xba, 0x3b, 0xf3, 0xb5, 0x08, 0x6c, 0x93, 0x57, 0xb0, 0xfb, 0xac,
	0xbf, 0xb1, 0x00, 0x1c, 0xc8, 0x95, 0x5e, 0xb6, 0x64, 0xaa, 0x3e, 0x31, 0x9c, 0x96, 0xd2, 0x7f,
	0xda, 0xf5, 0xe0, 0x42, 0xcd, 0x36, 0xed, 0x65, 0x3c, 0xdb, 0xdb, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x42, 0xd6, 0x2d, 0x01, 0x48, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/customer.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "customer.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/fpl.proto",
}

// FPLClient is the client API for FPL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FPLClient interface {
	GetNumberOfPlayers(ctx context.Context, in *NumPlayerRequest, opts ...grpc.CallOption) (*NumPlayers, error)
}

type fPLClient struct {
	cc *grpc.ClientConn
}

func NewFPLClient(cc *grpc.ClientConn) FPLClient {
	return &fPLClient{cc}
}

func (c *fPLClient) GetNumberOfPlayers(ctx context.Context, in *NumPlayerRequest, opts ...grpc.CallOption) (*NumPlayers, error) {
	out := new(NumPlayers)
	err := c.cc.Invoke(ctx, "/customer.FPL/getNumberOfPlayers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FPLServer is the server API for FPL service.
type FPLServer interface {
	GetNumberOfPlayers(context.Context, *NumPlayerRequest) (*NumPlayers, error)
}

func RegisterFPLServer(s *grpc.Server, srv FPLServer) {
	s.RegisterService(&_FPL_serviceDesc, srv)
}

func _FPL_GetNumberOfPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FPLServer).GetNumberOfPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.FPL/GetNumberOfPlayers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FPLServer).GetNumberOfPlayers(ctx, req.(*NumPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FPL_serviceDesc = grpc.ServiceDesc{
	ServiceName: "customer.FPL",
	HandlerType: (*FPLServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getNumberOfPlayers",
			Handler:    _FPL_GetNumberOfPlayers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/fpl.proto",
}
